#server:
#  port: 8082
#  spring:
#    active: loga
#---
#spring:
#  profile: loga
#  datasource:
#    password: rajsabariloga
#    url: jdbc:mysql://localhost:3306/spring-loga
#    username: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#---
